# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_auto_20151002_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=2048)),
                ('content', models.TextField()),
                ('twitter_link', models.CharField(max_length=4096)),
                ('linkedin_link', models.CharField(max_length=4096)),
                ('email_link', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('link_text', models.CharField(max_length=512)),
                ('target', models.CharField(choices=[('_blank', 'New window'), ('_self', 'Same window')], default='_self', max_length=128)),
                ('order', models.PositiveIntegerField(default='0')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('link_text', models.CharField(max_length=512)),
                ('target', models.CharField(choices=[('_blank', 'New window'), ('_self', 'Same window')], default='_self', max_length=128)),
                ('order', models.PositiveIntegerField(default='0')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'ordering': ['order', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='footerlink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='footer.FooterLinkGroup'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page'),
        ),
    ]
